### ISSUE TITLE
antiwarp & wireframe glow

### ISSUE THREAD

**Issue by canedoly** [M-FeD/Fedoraware#173]
it doesn't work idk why, In my older build of fedoraware it works fine

**Comment by canedoly** [comment]
there are also some weird lines when i use wireframe glow

**Comment by M-FeD** [comment]
the anti warp is fucked because i still have absolutely no idea how to make it good
wireframe glow line idk doesnt happen for me

**Comment by canedoly** [comment]
the old one was fine but in a specific commit [https://github.com/M-FeD/Fedoraware/commit/bbf5981d90717e6d3422c80e578879c59cfcbd8f](url) it just stopped working

**Comment by M-FeD** [comment]
yeah i know why its fucked but it was shit then too

**Comment by canedoly** [comment]
yeah it was shit, but it still tried to stop warping you while now you just warp with the dt

**Comment by M-FeD** [comment]
i mean i personally find it nicer as it is at the moment because with the previous anti warp if you changed direction it would like fuck you around making stuff like dt'ing sentries around corners reeeeeeeeally aids because you'd like peak with dt and then dt and then go back around the corner and then you would die because the anti warp anti anti warped you into the sentry again

**Comment by canedoly** [comment]
i guess your right, hope to see a decent anti warp in fedoraware in future
but yeah warping with dt can sometimes help
